### ISSUE TITLE
Crear Carpeta B_Bibliografia

### ISSUE THREAD

**Issue by Malvatyan** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-01#10]
En esta carpeta van a ir todos los datos del ESP32 que consigamos

**Comment by ulisesaale** [comment]
Procesador ESP32

 

En esta humilde casa somos muy partidarios y entusiastas del NodeMCU que incluye un chip Esp8266 12E y que recomendamos habitualmente a quién quiera iniciarse en el mundillo de la IOT y las comunicaciones WIFI.

Este chip hace ya unos años que se encuentra entre nosotros y siempre ha sido una de las formas mas sencillas y baratas de proporcionar WIFI a nuestros Arduinos. Lo curioso es que la comunidad ha desarrollado un pluggin que lo convierte ademas en un procesador compatible arduino que incluye WIFI siendo ademas compatible con las librerías oficiales.

Pero ya hace un año que salió un nuevo chip de espressif llamado ESP32 que es el sucesor del Esp8266 (Que no sustituto) con una serie de especificaciones impresionantes, y hemos estado esperando a que se estabilizase un poco el software necesario para que lo pudiésemos usar.

Aun esta un poco verde el asunto pero no puedo resistirme a presentaros el módulo porque es una autentica bomba y algo que solito puede soportar la IOT sin despeinarse.

Verán que aun hay cosas que aun están en fase de desarrollo como iremos viendo, pero creo que ya es el momento de que en esta caso hagamos la presentación del ESP32 porque creo que les va a gustar.

El ESP32 es un procesador del fabricante chino Espressif que viene con unas especificaciones espectaculares:
 

    Procesador dual core Xtensa® LX6 de 32 bits
    Es compatible Arduino con el pluggin adecuado (Enseguida vamos)
    Velocidad de reloj : Entre 160 Mhz y 240 Mhz
    520 Kb de RAM
    Wifi integrado: Acces point & Station
    Bluetooth 4.2 2.4 Ghz; BT 2.0 y 4.0 BLE
    36 GPIO pins.
    16 x Analog-to-Digital Converter (ADC) de 12 bits de resolución y se pueden programar con límite de entrada a 1V, 2 V y 4V
    2 x Digital to Analog converter DAC de 8 bits.
    Pueden definirse hasta 16 canales de PWM.
    2 x UART o puertas serie
    2 x I2C channels y 4 x SPI channels.
    La cosa sigue pero mejor lo dejamos aquí para no asustar.
