### ISSUE TITLE
Trabajo Colaborativo 2 - PCB

### ISSUE THREAD

**Issue by Malvatyan** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-01#104]

**Comment by cande2323** [comment]
Crear componentes para el eps32 a proteun

**Comment by cande2323** [comment]
[trabajo Colaborativo.pdf](https://github.com/ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-01/files/11362735/trabajo.Colaborativo.pdf)

Comit , rama #129

**Comment by cande2323** [comment]
#129
