### ISSUE TITLE
Trabajo Colaborativo 2 -Documentacion

### ISSUE THREAD

**Issue by Malvatyan** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-01#106]

**Comment by cande2323** [comment]
[trabajo Colaborativo.pdf](https://github.com/ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-01/files/11362724/trabajo.Colaborativo.pdf)

**Comment by Agustincorreag91** [comment]
Se sube documento pdf indicando pasos realizados para la puesta en marcha de nuestro web server.
