### ISSUE TITLE
Crear Carpeta D_ Proyecto

### ISSUE THREAD

**Issue by Malvatyan** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-01#12]
Acá vamos a poner los datos, info y cosas asociadas al proyecto en si mismo

**Comment by Malvatyan** [comment]
Dentro de la carpeta proyecto hay que crear 3 carpetas más: Hardware, Software y Video

**Comment by cande2323** [comment]
genial
