### ISSUE TITLE
Definir la historia de usuario

### ISSUE THREAD

**Issue by ulisesaale** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-01#56]
- # Uh#1Tk#1Int_x : Cargar nombre en el readme principal.
- # Uh#1Tk#2Int_x : Actualizar documentación ESP32
- # Uh#1Tk#3Int_x : Actualizar Bibliotecas / Recursos

**Comment by gastonloco** [comment]
se creo la historia de usuario #69
