### ISSUE TITLE
Documentación ESP32

### ISSUE THREAD

**Issue by Malvatyan** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-01#7]
El ESP32 es un microcontrolador de bajo costo y bajo consumo de energía desarrollado por la compañía china Espressif Systems. Es un dispositivo altamente integrado que combina un procesador de doble núcleo, conectividad Wi-Fi y Bluetooth, y una amplia variedad de periféricos, lo que lo hace ideal para aplicaciones IoT (Internet de las cosas).

El ESP32 tiene una arquitectura basada en el procesador Xtensa LX6 de 32 bits de Cadence Design Systems, con frecuencia de reloj de hasta 240 MHz, y cuenta con una memoria flash integrada para almacenamiento de programas y datos. También incluye una unidad de procesamiento gráfico (GPU) que puede ser utilizada para acelerar la renderización de gráficos y la decodificación de video.

Además de su potencia de procesamiento, el ESP32 también es conocido por su conectividad inalámbrica, ya que cuenta con Wi-Fi y Bluetooth integrados, lo que lo hace muy útil para aplicaciones de IoT que requieren conectividad inalámbrica. También tiene una amplia variedad de periféricos, incluyendo interfaces de comunicación como SPI, I2C y UART, así como entradas analógicas y GPIOs.

En resumen, el ESP32 es un microcontrolador altamente integrado y de bajo costo que combina un procesador de doble núcleo, conectividad Wi-Fi y Bluetooth, y una amplia variedad de periféricos, lo que lo hace ideal para aplicaciones IoT y de bajo consumo de energía.

![image](https://user-images.githubusercontent.com/129911584/232246354-6c1edf13-8521-4efb-a771-b9b30d7ebf8d.png)

**Comment by gastonloco** [comment]
#7
