### ISSUE TITLE
Trabajo Colaborativo 2 - Micro esp32

### ISSUE THREAD

**Issue by gastonloco** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-01#83]
Se debe desarrollar un web server con el esp32, de manera de poder
acceder a el desde el celular y poder ver los siguientes parámetros:

- 4 Entradas Analógicas
- 4 Entradas Digitales

Además, poder actuar sobre

- 4 Salidas Digitales

**Comment by Agustincorreag91** [comment]
se accede de manera correcta a nuestro web server, en donde nos permite interactuar con las entradas digitales.

![web server esp32](https://user-images.githubusercontent.com/129911123/235357267-5a15d511-b0bd-4123-bc06-4d0715695eee.jpg)
