### ISSUE TITLE
Trabajo Colaborativo 2 - protocolos de red y la configuración

### ISSUE THREAD

**Issue by gastonloco** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-01#84]
conocer los protocolos de red y la configuración de la conexión WiFi del ESP32 para que se pueda acceder al web server desde un celular.

**Comment by joacorta** [comment]
se deja habilitada la configuración para la conexión a una red wifi, con tcp/ipV4
