### ISSUE TITLE
Trabajo Colaborativo 2 - Documentación

### ISSUE THREAD

**Issue by gastonloco** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-01#88]
Es un documento que describe detalladamente cómo ensamblar los componentes en la PCB, incluyendo la orientación correcta de los componentes, la soldadura de los pines y otros detalles importantes.

**Comment by cande2323** [comment]
[trabajo Colaborativo.pdf](https://github.com/ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-01/files/11360690/trabajo.Colaborativo.pdf)

**Comment by Agustincorreag91** [comment]
se suben documentos pdf.
