### ISSUE TITLE
Definir grupo SCRUM

### ISSUE THREAD

**Issue by Malvatyan** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-01#9]
Acá ponemos que hacemos cada quien en el grupo

**Comment by ulisesaale** [comment]
Yo soy Analista de Negocio - Ulises Ale

**Comment by Malvatyan** [comment]
Scrum Master - Matias Humaran

**Comment by Agustincorreag91** [comment]
yo estaría formando parte del scrum team. Agustín Correa Guzman

**Comment by joacorta** [comment]
Yo soy formo parte del Scrum team y me desempeño en el rol de Desarrollador.
