### ISSUE TITLE
TP4- Configuración del entorno de programación

### ISSUE THREAD

**Issue by gastonloco** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-01#90]
Descargar e instalar las herramientas necesarias, incluyendo VSCode, PlatformIO y la biblioteca de Arduino para ESP32. Configurar la conexión del ESP32 con la computadora.

**Comment by Agustincorreag91** [comment]
Se instala vscode, se instala extensión platformio y se inicializa un nuevo proyecto, instalando biblioteca Arduino para plataforma ESP32 devkit.
Para la correcta conexión, se instalan drivers Silicon Labs CP210x USB to UART Bridge para que PC reconozca el ESP32.
